name: Generate GitHub Actions IP List

on:
  schedule:
    - cron: '0 0 * * *' # Roda todos os dias à meia-noite
  workflow_dispatch: # Permite rodar manualmente

# 1. Adicionamos a permissão explícita de escrita para o token da Action
permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 2. Atualizamos para a v4 para resolver o aviso do Node.js 20/24
      - uses: actions/checkout@v4 
      
      - name: Fetch and Parse GitHub IPs
        run: |
          # Baixa o JSON e usa o 'jq' para extrair a lista 'actions' em texto plano
          curl -s https://api.github.com/meta | jq -r '.actions[]' > github_actions_ips.txt
          
      - name: Commit and Push changes
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add github_actions_ips.txt
          # Só faz o commit se houver mudanças
          git diff --quiet && git diff --staged --quiet || git commit -m "Update IP list"
          git push
